name: Build, Publish and Deploy to Azure App Services

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./src/Cpnucleo.API"

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json

    - name: Install dependencies
      run: dotnet restore        

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        updateAssemblyInfo: true

    - name: Build project
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.GitVersion_SemVer }} /p:SourceLinkCreate=true /p:PublicRelease=true

    - name: Unit Tests
      working-directory: "./src/Cpnucleo.Application.Test"
      run: dotnet test   

    - name: Architecture Tests
      working-directory: "./src/Cpnucleo.Architecture.Test"
      run: dotnet test

  build-docker-image:
    # needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        # push: true
        file: ./src/Cpnucleo.API/Dockerfile
        tags: cpnucleo/cpnucleo-api:latest
        build-args: |
          DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
          QUEUE_CONNECTION_STRING=${{ secrets.QUEUE_CONNECTION_STRING }}
          SIGNALR_CONNECTION_STRING=CCCCCC

    - name: Test Secrets Value
      run: echo "TEST VAR - ${{ secrets.DB_CONNECTION_STRING }}"

    - name: Test Secrets Value
      run: echo "TEST VAR - ${{ secrets.QUEUE_CONNECTION_STRING }}"
    
    - name: Test Secrets Value
      run: echo "TEST VAR - ${{ secrets.SIGNALR_CONNECTION_STRING }}"      